'use client';

import React, { useState } from 'react';
import { create } from 'zustand';
import { X, ShoppingBag, ArrowRight, MessageSquare, MapPin, User, Phone, Mail, CreditCard } from 'lucide-react';
import { useCartStore } from '@/store/cart.store';
import { publicApi } from '@/lib/api';
import { formatCurrency } from '@/lib/utils';
import { Spinner } from '@/components/ui/Spinner';
import { toast } from 'sonner';

interface CartDrawerState {
  isOpen: boolean;
  open: () => void;
  close: () => void;
}

export const useCartDrawerStore = create<CartDrawerState>((set) => ({
  isOpen: false,
  open: () => set({ isOpen: true }),
  close: () => set({ isOpen: false }),
}));

interface CartDrawerProps {
  storeSlug: string;
}

export function CartDrawer({ storeSlug }: CartDrawerProps) {
  const { isOpen, close } = useCartDrawerStore();
  const { items, updateQty, removeItem, clearCart } = useCartStore();
  const [step, setStep] = useState<'cart' | 'checkout'>('cart');
  const [loading, setLoading] = useState(false);

  // Form state
  const [form, setForm] = useState({
    customerName: '',
    customerPhone: '',
    customerWhatsapp: '',
    customerEmail: '',
    deliveryAddress: '',
    notes: '',
    paymentMethod: 'whatsapp',
  });

  if (!isOpen) return null;

  const subtotal = items.reduce((sum, item) => sum + parseFloat(item.price) * item.quantity, 0);
  const currency = items[0]?.storeSlug === storeSlug ? 'ZMW' : 'ZMW'; // fallback currency

  const handleCheckout = async (e: React.FormEvent) => {
    e.preventDefault();
    if (items.length === 0) return;

    if (!form.customerName || !form.customerWhatsapp || !form.deliveryAddress) {
      toast.error('Please fill in all required fields (Name, WhatsApp, and Address)');
      return;
    }

    setLoading(true);
    try {
      const payload = {
        storeSlug,
        items: items.map((i) => ({
          productId: i.productId,
          quantity: i.quantity,
        })),
        customerName: form.customerName,
        customerPhone: form.customerPhone || undefined,
        customerWhatsapp: form.customerWhatsapp,
        customerEmail: form.customerEmail || undefined,
        deliveryAddress: form.deliveryAddress,
        notes: form.notes || undefined,
        paymentMethod: form.paymentMethod,
      };

      const { data } = await publicApi.post('/orders', payload);
      toast.success('Order placed! Redirecting to WhatsApp...');
      
      // Clear cart and state
      clearCart();
      setStep('cart');
      close();

      // Redirect to WhatsApp link generated by backend
      if (data.data?.whatsappUrl) {
        window.location.href = data.data.whatsappUrl;
      }
    } catch (err: any) {
      console.error(err);
      toast.error(err?.response?.data?.error?.message ?? 'Failed to place order. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 overflow-hidden">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/40 backdrop-blur-sm transition-opacity duration-300"
        onClick={close}
      />

      <div className="absolute inset-y-0 right-0 max-w-full flex pl-10">
        <div className="w-screen max-w-md transform transition-transform duration-300 ease-out bg-[var(--background)] border-l border-[var(--border)] shadow-2xl flex flex-col h-full">
          {/* Header */}
          <div className="px-6 py-5 border-b border-[var(--border)] flex items-center justify-between">
            <h2 className="text-lg font-display font-bold text-[var(--text-primary)] flex items-center gap-2">
              <ShoppingBag className="w-5 h-5 text-[var(--brand)]" />
              {step === 'cart' ? 'Shopping Cart' : 'Checkout Details'}
            </h2>
            <button 
              onClick={close}
              className="p-2 -mr-2 text-[var(--text-secondary)] hover:text-[var(--text-primary)] rounded-lg hover:bg-[var(--surface-2)] transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto px-6 py-4">
            {items.length === 0 ? (
              <div className="h-full flex flex-col items-center justify-center text-center py-12">
                <div className="w-16 h-16 rounded-full bg-[var(--brand-light)] text-[var(--brand)] flex items-center justify-center mb-4">
                  <ShoppingBag className="w-8 h-8" />
                </div>
                <h3 className="font-semibold text-lg text-[var(--text-primary)]">Your cart is empty</h3>
                <p className="text-sm text-[var(--text-secondary)] mt-1 max-w-xs">
                  Go back and browse products to add them to your cart.
                </p>
              </div>
            ) : step === 'cart' ? (
              /* Step 1: Cart list */
              <div className="space-y-4">
                {items.map((item) => (
                  <div key={item.productId} className="flex gap-4 p-3 rounded-xl border border-[var(--border)] bg-[var(--surface-2)]">
                    <div className="w-16 h-16 rounded-lg bg-[var(--surface-3)] overflow-hidden shrink-0 flex items-center justify-center text-2xl relative">
                      {item.image ? (
                        <img src={item.image} alt={item.name} className="object-cover w-full h-full" />
                      ) : (
                        '📦'
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <h4 className="font-medium text-sm text-[var(--text-primary)] truncate">{item.name}</h4>
                      <p className="text-xs text-[var(--brand)] font-semibold mt-0.5">{formatCurrency(item.price, currency)}</p>
                      
                      <div className="flex items-center justify-between mt-2">
                        <div className="flex items-center gap-2 bg-[var(--surface-3)] border border-[var(--border)] rounded-md px-1 py-0.5">
                          <button
                            onClick={() => updateQty(item.productId, item.quantity - 1)}
                            className="px-1.5 py-0.5 hover:bg-[var(--surface-2)] rounded text-xs font-bold"
                          >
                            -
                          </button>
                          <span className="text-xs font-semibold w-5 text-center">{item.quantity}</span>
                          <button
                            onClick={() => updateQty(item.productId, item.quantity + 1)}
                            disabled={!item.allowBackorder && item.quantity >= item.maxStock}
                            className="px-1.5 py-0.5 hover:bg-[var(--surface-2)] rounded text-xs font-bold disabled:opacity-40"
                          >
                            +
                          </button>
                        </div>
                        <button
                          onClick={() => removeItem(item.productId)}
                          className="text-xs text-red-500 hover:underline font-medium"
                        >
                          Remove
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              /* Step 2: Form checkout */
              <form onSubmit={handleCheckout} id="checkout-form" className="space-y-4">
                <div>
                  <label className="label flex items-center gap-1.5">
                    <User className="w-3.5 h-3.5 text-[var(--text-muted)]" /> Full Name <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="text"
                    required
                    className="input"
                    placeholder="John Doe"
                    value={form.customerName}
                    onChange={(e) => setForm({ ...form, customerName: e.target.value })}
                  />
                </div>

                <div>
                  <label className="label flex items-center gap-1.5">
                    <Phone className="w-3.5 h-3.5 text-[var(--text-muted)]" /> WhatsApp Number <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="tel"
                    required
                    className="input"
                    placeholder="e.g. +260977123456"
                    value={form.customerWhatsapp}
                    onChange={(e) => setForm({ ...form, customerWhatsapp: e.target.value })}
                  />
                  <p className="text-[10px] text-[var(--text-muted)] mt-1">
                    Include country code (e.g. +260 for Zambia)
                  </p>
                </div>

                <div>
                  <label className="label flex items-center gap-1.5">
                    <Phone className="w-3.5 h-3.5 text-[var(--text-muted)]" /> Secondary Phone (Optional)
                  </label>
                  <input
                    type="tel"
                    className="input"
                    placeholder="e.g. 0977123456"
                    value={form.customerPhone}
                    onChange={(e) => setForm({ ...form, customerPhone: e.target.value })}
                  />
                </div>

                <div>
                  <label className="label flex items-center gap-1.5">
                    <Mail className="w-3.5 h-3.5 text-[var(--text-muted)]" /> Email Address (Optional)
                  </label>
                  <input
                    type="email"
                    className="input"
                    placeholder="john@example.com"
                    value={form.customerEmail}
                    onChange={(e) => setForm({ ...form, customerEmail: e.target.value })}
                  />
                </div>

                <div>
                  <label className="label flex items-center gap-1.5">
                    <MapPin className="w-3.5 h-3.5 text-[var(--text-muted)]" /> Delivery Address <span className="text-red-500">*</span>
                  </label>
                  <textarea
                    required
                    rows={3}
                    className="input resize-none"
                    placeholder="House 12, President Avenue, Lusaka"
                    value={form.deliveryAddress}
                    onChange={(e) => setForm({ ...form, deliveryAddress: e.target.value })}
                  />
                </div>

                <div>
                  <label className="label flex items-center gap-1.5">
                    <MessageSquare className="w-3.5 h-3.5 text-[var(--text-muted)]" /> Order Notes (Optional)
                  </label>
                  <textarea
                    rows={2}
                    className="input resize-none"
                    placeholder="e.g. Call before delivery, red color preferred..."
                    value={form.notes}
                    onChange={(e) => setForm({ ...form, notes: e.target.value })}
                  />
                </div>

                <div>
                  <label className="label flex items-center gap-1.5">
                    <CreditCard className="w-3.5 h-3.5 text-[var(--text-muted)]" /> Payment Method
                  </label>
                  <select
                    className="input"
                    value={form.paymentMethod}
                    onChange={(e) => setForm({ ...form, paymentMethod: e.target.value })}
                  >
                    <option value="whatsapp">Order & Pay via WhatsApp (Cash/MoMo)</option>
                    <option value="mobile_money">Mobile Money Direct</option>
                    <option value="cash">Cash on Delivery</option>
                  </select>
                </div>
              </form>
            )}
          </div>

          {/* Footer */}
          {items.length > 0 && (
            <div className="px-6 py-5 border-t border-[var(--border)] bg-[var(--surface-2)] space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium text-[var(--text-secondary)]">Subtotal</span>
                <span className="text-lg font-bold text-[var(--text-primary)]">{formatCurrency(subtotal, currency)}</span>
              </div>

              {step === 'cart' ? (
                <button
                  onClick={() => setStep('checkout')}
                  className="btn-primary w-full py-3 text-sm flex items-center justify-center gap-1.5"
                >
                  Proceed to Checkout
                  <ArrowRight className="w-4 h-4" />
                </button>
              ) : (
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => setStep('cart')}
                    className="btn-secondary flex-1 py-3 text-sm"
                    disabled={loading}
                  >
                    Back to Cart
                  </button>
                  <button
                    type="submit"
                    form="checkout-form"
                    disabled={loading}
                    className="btn-whatsapp flex-1 py-3 text-sm flex items-center justify-center gap-1.5"
                  >
                    {loading ? (
                      <Spinner size="sm" />
                    ) : (
                      <>
                        Confirm Order
                        <ArrowRight className="w-4 h-4" />
                      </>
                    )}
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
