'use client';

import { useRef, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ChevronLeft, ChevronRight, Flame, Heart, Leaf, Minus, Pill, Plus, ShoppingCart, Utensils } from 'lucide-react';
import { formatCurrency } from '@/lib/utils';
import { PREDEFINED_DISPLAY_TYPES, parseProductAttributes } from './product-attributes';
import type { ProductAttributes, ProductCardProps, Product } from './storefront.types';

function BusinessTypeBadges({ businessType, attributes }: { businessType: string; attributes: ProductAttributes }) {
  const badges: React.ReactNode[] = [];
  if (businessType === 'RESTAURANT') {
    if (attributes.customAttributes.some((attribute) => attribute.name.toLowerCase().includes('spice'))) badges.push(<span key="spicy" className="text-xs bg-orange-100 text-orange-700 px-2 py-0.5 rounded-full flex items-center gap-1"><Flame className="w-3 h-3" /> Spicy</span>);
    if (attributes.customAttributes.some((attribute) => attribute.name.toLowerCase().includes('veg') || attribute.values.some((value) => value.toLowerCase().includes('veg')))) badges.push(<span key="veg" className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full flex items-center gap-1"><Leaf className="w-3 h-3" /> Veg</span>);
    if (attributes.customAttributes.some((attribute) => attribute.values.some((value) => value.toLowerCase().includes('non-veg') || value.toLowerCase().includes('meat')))) badges.push(<span key="nonveg" className="text-xs bg-red-100 text-red-700 px-2 py-0.5 rounded-full flex items-center gap-1"><Utensils className="w-3 h-3" /> Non-Veg</span>);
  }
  if (businessType === 'PHARMACY') {
    const dosage = attributes.customAttributes.find((attribute) => attribute.name.toLowerCase().includes('dosage') || attribute.name.toLowerCase().includes('form'));
    if (dosage) badges.push(<span key="dosage" className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full flex items-center gap-1"><Pill className="w-3 h-3" /> {dosage.values[0]}</span>);
  }
  return badges.length ? <div className="flex flex-wrap gap-1.5 mt-2">{badges}</div> : null;
}

function ProductAttributeDisplay({ attributes, businessType, selectedColor, onColorSelect }: { attributes: ProductAttributes; businessType: string; selectedColor?: { name: string; hex: string }; onColorSelect: (color: { name: string; hex: string }) => void }) {
  if (!attributes.colors.length && !attributes.sizes.length && !attributes.customAttributes.length && !Object.keys(attributes.dynamicFields || {}).length) return null;

  // Show sizes for all business types — the fix for the "Display Extra Information" bug
  const sizeLabel = businessType === 'RESTAURANT' ? 'Portions:' : 'Sizes:';
  const showSizes = attributes.sizes.length > 0;

  // Show relevant dynamic fields as info pills (e.g. brand, model, warranty, ingredients)
  const dynamicEntries = Object.entries(attributes.dynamicFields || {}).filter(([, v]) => !!v).slice(0, 3);

  return <div className="mt-3 space-y-2">
    {attributes.colors.length > 0 && <div className="flex items-center gap-2"><span className="text-[10px] text-slate-500 uppercase tracking-wider">Colors:</span><div className="flex gap-1">{attributes.colors.slice(0, 5).map((color) => <button key={color.name} onClick={() => onColorSelect(color)} className={`w-5 h-5 rounded-full border-2 shadow-sm hover:scale-110 transition-transform ${selectedColor?.name === color.name ? 'border-slate-900 ring-2 ring-slate-300' : 'border-white'}`} style={{ backgroundColor: color.hex }} title={color.name} />)}{attributes.colors.length > 5 && <span className="text-[10px] text-slate-400">+{attributes.colors.length - 5}</span>}</div></div>}
    {showSizes && <div className="flex items-center gap-2"><span className="text-[10px] text-slate-500 uppercase tracking-wider">{sizeLabel}</span><div className="flex gap-1 flex-wrap">{attributes.sizes.slice(0, 4).map((size) => <span key={size} className="text-[10px] bg-slate-100 px-2 py-0.5 rounded border border-slate-200">{size}</span>)}{attributes.sizes.length > 4 && <span className="text-[10px] text-slate-400">+{attributes.sizes.length - 4}</span>}</div></div>}
    {dynamicEntries.length > 0 && <div className="flex flex-wrap gap-1">{dynamicEntries.map(([key, value]) => <span key={key} className="text-[10px] rounded-full border border-slate-200 bg-slate-50 px-2 py-0.5 text-slate-600 capitalize">{key}: {value}</span>)}</div>}
    {attributes.customAttributes.length > 0 && <div className="flex flex-wrap gap-1">{attributes.customAttributes.slice(0, 2).map((attribute) => <span key={attribute.name} className="text-[10px] rounded-full border border-slate-200 bg-slate-50 px-2 py-0.5 text-slate-600">{attribute.name}: {attribute.values[0]}</span>)}</div>}
  </div>;
}


export function ProductCardStandard({ product, storeSlug, store, mounted, wishlist, toggleWishlist, addItem, updateQty, getItem }: ProductCardProps) {
  const attributes = parseProductAttributes(product.tags);
  const [selectedColor, setSelectedColor] = useState(attributes.colors[0]);
  const inCart = getItem(product.id);
  const isOutOfStock = product.trackInventory && !product.allowBackorder && product.stockQuantity === 0;
  const discount = product.compareAtPrice ? Math.round((1 - parseFloat(product.price) / parseFloat(product.compareAtPrice)) * 100) : null;
  const displayBadge = product.tags?.map((tag) => tag.toLowerCase()).find((tag) => tag in PREDEFINED_DISPLAY_TYPES);
  return <div className={`group flex flex-col overflow-hidden rounded-xl border border-slate-200 bg-white hover:border-[var(--brand)] transition-all duration-300 hover:shadow-[0_0_24px_rgba(15,110,86,0.06)] ${isOutOfStock ? 'opacity-60' : ''}`}>
    <div className="relative aspect-[4/5] overflow-hidden bg-slate-50"><Link href={`/${storeSlug}/products/${product.slug}`}>{product.images?.[0] ? <Image src={product.images[0]} alt={product.name} fill className="object-cover transition-transform duration-500 group-hover:scale-105" sizes="(max-width: 640px) 50vw, 25vw" /> : <div className="absolute inset-0 flex items-center justify-center text-5xl">📦</div>}</Link><div className="absolute inset-x-3 top-3 flex items-start justify-between gap-2 pointer-events-none">{discount && discount > 0 && <span className="rounded-full bg-red-500 px-2.5 py-1 text-[10px] font-black text-white shadow-lg">-{discount}%</span>}{displayBadge && <span className={`rounded-full px-2.5 py-1 text-[10px] font-black text-white shadow-lg ${PREDEFINED_DISPLAY_TYPES[displayBadge].class}`}>{PREDEFINED_DISPLAY_TYPES[displayBadge].label}</span>}</div><div className="absolute inset-x-3 top-3 flex justify-end opacity-0 group-hover:opacity-100 transition-all pointer-events-auto"><button onClick={() => toggleWishlist(product.id, product.name)} className={`p-2 rounded-full shadow-lg backdrop-blur bg-white/90 border border-slate-200 ${wishlist.has(product.id) ? 'text-rose-500' : 'text-slate-400'}`}><Heart className="w-3.5 h-3.5" /></button></div></div>
    <div className="flex flex-1 flex-col gap-2 p-4">{product.category && <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--brand)] font-mono">{product.category.name}</p>}<Link href={`/${storeSlug}/products/${product.slug}`} className="line-clamp-2 flex-1 text-sm font-bold leading-5 text-slate-900 sm:text-base hover:text-[var(--brand)]">{product.name}</Link><BusinessTypeBadges businessType={store.businessType} attributes={attributes} /><ProductAttributeDisplay attributes={attributes} businessType={store.businessType} selectedColor={selectedColor} onColorSelect={setSelectedColor} />{store.businessType === 'RESTAURANT' && <div className="mt-2 flex flex-wrap gap-1">{['Dine-In', 'Delivery', 'Pickup'].map((option) => <span key={option} className="rounded-full border border-slate-200 bg-slate-50 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-slate-600">{option}</span>)}</div>}<div className="mt-2 flex items-center justify-between gap-2"><span className="text-base font-black text-[var(--brand)]">{formatCurrency(product.price)}</span>{mounted && inCart ? <div className="flex items-center gap-1 bg-slate-100 border border-slate-200 rounded-full p-0.5"><button onClick={() => updateQty(product.id, inCart.quantity - 1)} className="p-1 rounded-full hover:bg-slate-200"><Minus className="w-3 h-3" /></button><span className="text-xs font-bold px-1.5 text-slate-900">{inCart.quantity}</span><button onClick={() => updateQty(product.id, inCart.quantity + 1)} disabled={!product.allowBackorder && inCart.quantity >= product.stockQuantity} className="p-1 rounded-full hover:bg-slate-200"><Plus className="w-3 h-3" /></button></div> : <button onClick={() => addItem({ productId: product.id, name: product.name, price: product.price, image: product.images?.[0] || null, maxStock: product.stockQuantity, allowBackorder: product.allowBackorder, selectedColor }, storeSlug)} className="p-2 rounded-full bg-[var(--brand)] text-white hover:opacity-90" aria-label={`Add ${product.name} to cart`}><ShoppingCart className="w-4 h-4" /></button>}</div></div>
  </div>;
}

export function ProductCardCarousel({ products, ...props }: Omit<ProductCardProps, 'product'> & { products: Product[] }) { const ref = useRef<HTMLDivElement>(null); const scroll = (direction: 1 | -1) => ref.current?.scrollBy({ left: ref.current.clientWidth * 0.8 * direction, behavior: 'smooth' }); return <div className="relative"><div className="flex gap-2 mb-4"><button onClick={() => scroll(-1)} className="p-2 rounded-full border border-slate-200 bg-white"><ChevronLeft className="w-4 h-4" /></button><button onClick={() => scroll(1)} className="p-2 rounded-full border border-slate-200 bg-white"><ChevronRight className="w-4 h-4" /></button></div><div ref={ref} className="flex gap-4 overflow-x-auto scrollbar-none snap-x snap-mandatory pb-4">{products.map((product) => <div key={product.id} className="snap-start shrink-0 w-[280px]"><ProductCardStandard {...props} product={product} /></div>)}</div></div>; }

export function ProductCardCollage({ products, storeSlug }: Omit<ProductCardProps, 'product'> & { products: Product[] }) { return <div className="grid grid-cols-2 md:grid-cols-3 gap-4 auto-rows-[200px]">{products.map((product, index) => <Link key={product.id} href={`/${storeSlug}/products/${product.slug}`} className={`${index === 0 ? 'col-span-2 row-span-2' : ''} relative overflow-hidden rounded-xl border border-slate-200 bg-white hover:border-[var(--brand)] group`}>{product.images?.[0] ? <Image src={product.images[0]} alt={product.name} fill className="object-cover transition-transform duration-500 group-hover:scale-105" /> : <div className="absolute inset-0 flex items-center justify-center text-4xl bg-slate-50">📦</div>}<div className="absolute bottom-0 inset-x-0 p-4 bg-gradient-to-t from-black/60 to-transparent"><p className="text-white font-bold text-sm line-clamp-1">{product.name}</p><p className="text-white/90 text-xs font-mono">{formatCurrency(product.price)}</p></div></Link>)}</div>; }

export function ProductCardMagazine({ products, ...props }: Omit<ProductCardProps, 'product'> & { products: Product[] }) { const [featured, ...sideProducts] = products; if (!featured) return null; return <div className="space-y-6"><div className="relative rounded-2xl overflow-hidden border border-slate-200 bg-white group"><Link href={`/${props.storeSlug}/products/${featured.slug}`} className="block"><div className="aspect-[16/9] relative">{featured.images?.[0] ? <Image src={featured.images[0]} alt={featured.name} fill className="object-cover" /> : <div className="absolute inset-0 flex items-center justify-center text-6xl bg-slate-50">📦</div>}<div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent" /><div className="absolute bottom-0 inset-x-0 p-8"><p className="text-white/80 text-xs font-bold uppercase tracking-wider mb-2">Featured</p><h3 className="text-white font-black text-2xl sm:text-3xl line-clamp-2 mb-2">{featured.name}</h3><p className="text-white/90 text-sm line-clamp-2 mb-4">{featured.description}</p><div className="flex items-center gap-3"><span className="text-white font-black text-xl">{formatCurrency(featured.price)}</span><button onClick={(event) => { event.preventDefault(); props.addItem({ productId: featured.id, name: featured.name, price: featured.price, image: featured.images?.[0] || null, maxStock: featured.stockQuantity, allowBackorder: featured.allowBackorder }, props.storeSlug); }} className="px-4 py-2 bg-white text-slate-900 rounded-full font-bold text-sm">Add to Cart</button></div></div></div></Link></div><div className="grid grid-cols-2 gap-4">{sideProducts.slice(0, 4).map((product) => <ProductCardStandard key={product.id} {...props} product={product} />)}</div></div>; }

export function ProductCardSpotlight({ product, store, ...props }: ProductCardProps) { const attributes = parseProductAttributes(product.tags); const [selectedColor, setSelectedColor] = useState(attributes.colors[0]); const discount = product.compareAtPrice ? Math.round((1 - parseFloat(product.price) / parseFloat(product.compareAtPrice)) * 100) : null; return <div className="relative rounded-2xl overflow-hidden border border-slate-200 bg-white group"><Link href={`/${props.storeSlug}/products/${product.slug}`} className="block"><div className="aspect-[21/9] relative">{product.images?.[0] ? <Image src={product.images[0]} alt={product.name} fill className="object-cover" /> : <div className="absolute inset-0 flex items-center justify-center text-6xl bg-slate-50">📦</div>}<div className="absolute inset-0 bg-gradient-to-r from-black/70 via-black/40 to-transparent" /><div className="absolute inset-0 p-8 flex flex-col justify-center">{product.category && <p className="text-white/80 text-xs font-bold uppercase tracking-wider mb-2">{product.category.name}</p>}<h3 className="text-white font-black text-2xl sm:text-3xl line-clamp-2 mb-2">{product.name}</h3><p className="text-white/90 text-sm line-clamp-2 mb-4 max-w-lg">{product.description}</p><BusinessTypeBadges businessType={store.businessType} attributes={attributes} /><ProductAttributeDisplay attributes={attributes} businessType={store.businessType} selectedColor={selectedColor} onColorSelect={setSelectedColor} /><div className="flex items-center gap-4 mt-4"><div className="flex items-center gap-2"><span className="text-white font-black text-2xl">{formatCurrency(product.price)}</span>{discount && discount > 0 && <span className="text-white/60 line-through">{formatCurrency(product.compareAtPrice!)}</span>}</div><button onClick={(event) => { event.preventDefault(); props.addItem({ productId: product.id, name: product.name, price: product.price, image: product.images?.[0] || null, maxStock: product.stockQuantity, allowBackorder: product.allowBackorder, selectedColor }, props.storeSlug); }} className="px-6 py-3 bg-[var(--brand)] text-white rounded-full font-bold text-sm">Add to Cart</button></div></div></div></Link></div>; }
